/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package POS.pnl;

import POS.banks.Dlg_banks;
import POS.bir_session.Dlg_x_reading;
import POS.bir_session.Dlg_z_reading;
import POS.cash_drawer.*;
import POS.category.Dlg_category;
import POS.credit_cards.Dlg_credit_cards;
import POS.customers.Dlg_customers;
import POS.disbursements.Dlg_disbursements;
import POS.discounts.Dlg_discounts;
import POS.expenses.Dlg_expenses;
import POS.inv_category_group.Dlg_inv_category_group;
import POS.items.Dlg_items;
import POS.main.Main;
import POS.new_inventory.Dlg_new_inventory;
import POS.printing_assembly.Dlg_printing_assembly;
import POS.purchase_order.Dlg_purchase_order;
import POS.receipts.Dlg_receipts;
import POS.reports.*;
import POS.services.Dlg_services;
import POS.stock_transfer.Dlg_rpt_stock_transfer;
import POS.stock_transfer.Dlg_stock_transfer;
import POS.suppliers.Dlg_supplier;
import POS.tables.Dlg_tables;
import POS.touchscreen.Dlg_touchscreen;
import POS.touchscreen.Dlg_touchscreen_login;
import POS.uom.Dlg_uom;
import POS.users.Dlg_users;
import POS.util.Alert;
import POS.util.MyFrame;
import POS.util.Users;
import POS.voider.Dlg_voider;
import POS.waiters.Dlg_waiters;
import POS_order_specifications.Dlg_order_spefications;
import java.awt.*;
import javax.swing.*;
import mijzcx.synapse.desk.utils.Application;
import mijzcx.synapse.desk.utils.CloseDialog;

/**
 *
 * @author i1
 */
public class Pnl_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Pnl_Dashboard
     */
    public Pnl_Dashboard() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        transactions = new javax.swing.JMenu();
        cb_t_sales = new javax.swing.JMenuItem();
        cb_t_receipts = new javax.swing.JMenuItem();
        cb_t_stock_tranfer = new javax.swing.JMenuItem();
        cb_t_inventory_adjuster = new javax.swing.JMenuItem();
        cb_t_purchase_order = new javax.swing.JMenuItem();
        cb_t_voider = new javax.swing.JMenuItem();
        cb_t_disbursements = new javax.swing.JMenuItem();
        maintenance = new javax.swing.JMenu();
        cb_m_items = new javax.swing.JMenuItem();
        cb_m_category = new javax.swing.JMenuItem();
        cb_m_users = new javax.swing.JMenuItem();
        cb_m_uom = new javax.swing.JMenuItem();
        cb_m_supplier = new javax.swing.JMenuItem();
        cb_m_customers = new javax.swing.JMenuItem();
        cb_m_discounts = new javax.swing.JMenuItem();
        cb_m_banks = new javax.swing.JMenuItem();
        cb_m_services = new javax.swing.JMenuItem();
        cb_m_expenses = new javax.swing.JMenuItem();
        cb_m_credit_cards = new javax.swing.JMenuItem();
        cb_m_printing_assembly = new javax.swing.JMenuItem();
        cb_m_category_group = new javax.swing.JMenuItem();
        cb_m_waiters = new javax.swing.JMenuItem();
        cb_m_tables = new javax.swing.JMenuItem();
        cb_m_spec = new javax.swing.JMenuItem();
        reports = new javax.swing.JMenu();
        cb_r_sales = new javax.swing.JMenuItem();
        cb_r_sales_items = new javax.swing.JMenuItem();
        cb_r_cash_count = new javax.swing.JMenuItem();
        cb_r_receipts = new javax.swing.JMenuItem();
        cb_r_stock_transferred = new javax.swing.JMenuItem();
        cb_r_stocks_left_category = new javax.swing.JMenuItem();
        cb_r_stocks_left_supplier = new javax.swing.JMenuItem();
        cb_r_items = new javax.swing.JMenuItem();
        cb_r_purchase_order = new javax.swing.JMenuItem();
        cb_r_voider = new javax.swing.JMenuItem();
        cb_r_patronage_refund = new javax.swing.JMenuItem();
        cb_r_patronage_refund1 = new javax.swing.JMenuItem();
        bir = new javax.swing.JMenu();
        cb_b_x_reading = new javax.swing.JMenuItem();
        cb_b_z_reading = new javax.swing.JMenuItem();
        cb_b_reading_trails = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        stand_by = new javax.swing.JMenuItem();
        LOGOUT = new javax.swing.JMenuItem();
        my_trans = new javax.swing.JPopupMenu();
        my_maintenance = new javax.swing.JPopupMenu();
        my_reports = new javax.swing.JPopupMenu();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPopupMenu1.setBackground(new java.awt.Color(51, 153, 255));

        transactions.setBackground(new java.awt.Color(255, 255, 255));
        transactions.setForeground(new java.awt.Color(51, 51, 51));
        transactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N
        transactions.setText("Transactions");
        transactions.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        transactions.setOpaque(true);
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });

        cb_t_sales.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_sales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_sales.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/sales.png"))); // NOI18N
        cb_t_sales.setText("Sales");
        cb_t_sales.setOpaque(true);
        cb_t_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_salesActionPerformed(evt);
            }
        });
        transactions.add(cb_t_sales);

        cb_t_receipts.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/receipts.png"))); // NOI18N
        cb_t_receipts.setText("Receipts");
        cb_t_receipts.setOpaque(true);
        cb_t_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_receiptsActionPerformed(evt);
            }
        });
        transactions.add(cb_t_receipts);

        cb_t_stock_tranfer.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_stock_tranfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_stock_tranfer.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_stock_tranfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/stock_transfer.png"))); // NOI18N
        cb_t_stock_tranfer.setText("Stock Transfer");
        cb_t_stock_tranfer.setToolTipText("");
        cb_t_stock_tranfer.setOpaque(true);
        cb_t_stock_tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_stock_tranferActionPerformed(evt);
            }
        });
        transactions.add(cb_t_stock_tranfer);

        cb_t_inventory_adjuster.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_inventory_adjuster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_inventory_adjuster.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_inventory_adjuster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/items.png"))); // NOI18N
        cb_t_inventory_adjuster.setText("Inventory Adjuster");
        cb_t_inventory_adjuster.setOpaque(true);
        cb_t_inventory_adjuster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_inventory_adjusterActionPerformed(evt);
            }
        });
        transactions.add(cb_t_inventory_adjuster);

        cb_t_purchase_order.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_purchase_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_purchase_order.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_purchase_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_t_purchase_order.setText("Purchase Order");
        cb_t_purchase_order.setOpaque(true);
        cb_t_purchase_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_purchase_orderActionPerformed(evt);
            }
        });
        transactions.add(cb_t_purchase_order);

        cb_t_voider.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_voider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_voider.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_voider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_drop.png"))); // NOI18N
        cb_t_voider.setText("Voider");
        cb_t_voider.setOpaque(true);
        cb_t_voider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_voiderActionPerformed(evt);
            }
        });
        transactions.add(cb_t_voider);

        cb_t_disbursements.setBackground(new java.awt.Color(255, 102, 0));
        cb_t_disbursements.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_disbursements.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_disbursements.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer_item_pricing.png"))); // NOI18N
        cb_t_disbursements.setText("Disbursements");
        cb_t_disbursements.setOpaque(true);
        cb_t_disbursements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_disbursementsActionPerformed(evt);
            }
        });
        transactions.add(cb_t_disbursements);

        jPopupMenu1.add(transactions);

        maintenance.setBackground(new java.awt.Color(51, 153, 255));
        maintenance.setForeground(new java.awt.Color(255, 255, 255));
        maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/security_manager.png"))); // NOI18N
        maintenance.setText("MAINTENANCE");
        maintenance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        maintenance.setOpaque(true);

        cb_m_items.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/items.png"))); // NOI18N
        cb_m_items.setText("Items");
        cb_m_items.setOpaque(true);
        cb_m_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_itemsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_items);

        cb_m_category.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_category.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/category.png"))); // NOI18N
        cb_m_category.setText("Category");
        cb_m_category.setOpaque(true);
        cb_m_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_categoryActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_category);

        cb_m_users.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_users.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_users.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/users.png"))); // NOI18N
        cb_m_users.setText("Users");
        cb_m_users.setOpaque(true);
        cb_m_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_usersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_users);

        cb_m_uom.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_uom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_uom.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_uom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/uom.png"))); // NOI18N
        cb_m_uom.setText("Unit of Measure");
        cb_m_uom.setOpaque(true);
        cb_m_uom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_uomActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_uom);

        cb_m_supplier.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_supplier.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/suppliers.png"))); // NOI18N
        cb_m_supplier.setText("Supplier");
        cb_m_supplier.setOpaque(true);
        cb_m_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_supplierActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_supplier);

        cb_m_customers.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_customers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_customers.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer.png"))); // NOI18N
        cb_m_customers.setText("Customers");
        cb_m_customers.setOpaque(true);
        cb_m_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_customersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_customers);

        cb_m_discounts.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_discounts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_discounts.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_discounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer_item_pricing.png"))); // NOI18N
        cb_m_discounts.setText("Discounts");
        cb_m_discounts.setOpaque(true);
        cb_m_discounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_discountsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_discounts);

        cb_m_banks.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_banks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_banks.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_banks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_b.png"))); // NOI18N
        cb_m_banks.setText("Banks");
        cb_m_banks.setOpaque(true);
        cb_m_banks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_banksActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_banks);

        cb_m_services.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_services.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_services.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N
        cb_m_services.setText("Services");
        cb_m_services.setOpaque(true);
        cb_m_services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_servicesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_services);

        cb_m_expenses.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_expenses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_expenses.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_m_expenses.setText("Disbursements");
        cb_m_expenses.setOpaque(true);
        cb_m_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_expensesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_expenses);

        cb_m_credit_cards.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_credit_cards.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_credit_cards.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_credit_cards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_m_credit_cards.setText("Credit Cards");
        cb_m_credit_cards.setOpaque(true);
        cb_m_credit_cards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_credit_cardsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_credit_cards);

        cb_m_printing_assembly.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_printing_assembly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_printing_assembly.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_printing_assembly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/world_val.png"))); // NOI18N
        cb_m_printing_assembly.setText("Printing Assembly");
        cb_m_printing_assembly.setOpaque(true);
        cb_m_printing_assembly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_printing_assemblyActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_printing_assembly);

        cb_m_category_group.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_category_group.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_category_group.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_category_group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_category.png"))); // NOI18N
        cb_m_category_group.setText("Category Group");
        cb_m_category_group.setOpaque(true);
        cb_m_category_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_category_groupActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_category_group);

        cb_m_waiters.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_waiters.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_waiters.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_waiters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/user_item_maintenance.png"))); // NOI18N
        cb_m_waiters.setText("Waiters");
        cb_m_waiters.setOpaque(true);
        cb_m_waiters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_waitersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_waiters);

        cb_m_tables.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_tables.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_tables.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_tables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/user_item_maintenance.png"))); // NOI18N
        cb_m_tables.setText("Tables");
        cb_m_tables.setOpaque(true);
        cb_m_tables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_tablesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_tables);

        cb_m_spec.setBackground(new java.awt.Color(255, 102, 0));
        cb_m_spec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_spec.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_spec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/user_item_maintenance.png"))); // NOI18N
        cb_m_spec.setText("Order Specification");
        cb_m_spec.setOpaque(true);
        cb_m_spec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_specActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_spec);

        jPopupMenu1.add(maintenance);

        reports.setBackground(new java.awt.Color(51, 153, 255));
        reports.setForeground(new java.awt.Color(255, 255, 255));
        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        reports.setText("REPORTS");
        reports.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reports.setOpaque(true);

        cb_r_sales.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_sales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_sales.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales.png"))); // NOI18N
        cb_r_sales.setText("Sales by Transaction");
        cb_r_sales.setOpaque(true);
        cb_r_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_salesActionPerformed(evt);
            }
        });
        reports.add(cb_r_sales);

        cb_r_sales_items.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_sales_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_sales_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_sales_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_ledger.png"))); // NOI18N
        cb_r_sales_items.setText("Sales by Item");
        cb_r_sales_items.setToolTipText("");
        cb_r_sales_items.setOpaque(true);
        cb_r_sales_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_sales_itemsActionPerformed(evt);
            }
        });
        reports.add(cb_r_sales_items);

        cb_r_cash_count.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_cash_count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_cash_count.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_cash_count.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_b.png"))); // NOI18N
        cb_r_cash_count.setText("Cash Count/Expenses");
        cb_r_cash_count.setOpaque(true);
        cb_r_cash_count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_cash_countActionPerformed(evt);
            }
        });
        reports.add(cb_r_cash_count);

        cb_r_receipts.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/receipts.png"))); // NOI18N
        cb_r_receipts.setText("Receipts");
        cb_r_receipts.setOpaque(true);
        cb_r_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_receiptsActionPerformed(evt);
            }
        });
        reports.add(cb_r_receipts);

        cb_r_stock_transferred.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_stock_transferred.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stock_transferred.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stock_transferred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/orders_and_deliveries.png"))); // NOI18N
        cb_r_stock_transferred.setText("Stock Transfer");
        cb_r_stock_transferred.setOpaque(true);
        cb_r_stock_transferred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stock_transferredActionPerformed(evt);
            }
        });
        reports.add(cb_r_stock_transferred);

        cb_r_stocks_left_category.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_stocks_left_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stocks_left_category.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stocks_left_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stocks_left_category.setText("Stocks Left by Category");
        cb_r_stocks_left_category.setOpaque(true);
        cb_r_stocks_left_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stocks_left_categoryActionPerformed(evt);
            }
        });
        reports.add(cb_r_stocks_left_category);

        cb_r_stocks_left_supplier.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_stocks_left_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stocks_left_supplier.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stocks_left_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stocks_left_supplier.setText("Stocks Left by Supplier");
        cb_r_stocks_left_supplier.setOpaque(true);
        cb_r_stocks_left_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stocks_left_supplierActionPerformed(evt);
            }
        });
        reports.add(cb_r_stocks_left_supplier);

        cb_r_items.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_items.setText("Items by Category");
        cb_r_items.setOpaque(true);
        cb_r_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_itemsActionPerformed(evt);
            }
        });
        reports.add(cb_r_items);

        cb_r_purchase_order.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_purchase_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_purchase_order.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_purchase_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_r_purchase_order.setText("Purchase Order");
        cb_r_purchase_order.setOpaque(true);
        cb_r_purchase_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_purchase_orderActionPerformed(evt);
            }
        });
        reports.add(cb_r_purchase_order);

        cb_r_voider.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_voider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_voider.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_voider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_drop.png"))); // NOI18N
        cb_r_voider.setText("Voider");
        cb_r_voider.setOpaque(true);
        cb_r_voider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_voiderActionPerformed(evt);
            }
        });
        reports.add(cb_r_voider);

        cb_r_patronage_refund.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_patronage_refund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_patronage_refund.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_patronage_refund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales.png"))); // NOI18N
        cb_r_patronage_refund.setText("Patronage Refund");
        cb_r_patronage_refund.setOpaque(true);
        cb_r_patronage_refund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_patronage_refundActionPerformed(evt);
            }
        });
        reports.add(cb_r_patronage_refund);

        cb_r_patronage_refund1.setBackground(new java.awt.Color(255, 102, 0));
        cb_r_patronage_refund1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_patronage_refund1.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_patronage_refund1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/stock_take.png"))); // NOI18N
        cb_r_patronage_refund1.setText("Z Reading");
        cb_r_patronage_refund1.setOpaque(true);
        cb_r_patronage_refund1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_patronage_refund1ActionPerformed(evt);
            }
        });
        reports.add(cb_r_patronage_refund1);

        jPopupMenu1.add(reports);

        bir.setBackground(new java.awt.Color(51, 153, 255));
        bir.setForeground(new java.awt.Color(255, 255, 255));
        bir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/reports.PNG"))); // NOI18N
        bir.setText("BIR");
        bir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bir.setOpaque(true);

        cb_b_x_reading.setBackground(new java.awt.Color(255, 102, 0));
        cb_b_x_reading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_x_reading.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_x_reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_b_x_reading.setText("Sales Summary");
        cb_b_x_reading.setOpaque(true);
        cb_b_x_reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_x_readingActionPerformed(evt);
            }
        });
        bir.add(cb_b_x_reading);

        cb_b_z_reading.setBackground(new java.awt.Color(51, 153, 255));
        cb_b_z_reading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_z_reading.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_z_reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_ledger.png"))); // NOI18N
        cb_b_z_reading.setText("Z Reading");
        cb_b_z_reading.setOpaque(true);
        cb_b_z_reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_z_readingActionPerformed(evt);
            }
        });
        bir.add(cb_b_z_reading);

        cb_b_reading_trails.setBackground(new java.awt.Color(51, 153, 255));
        cb_b_reading_trails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_reading_trails.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_reading_trails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        cb_b_reading_trails.setText("X Reading");
        cb_b_reading_trails.setActionCommand("READING TRAILS");
        cb_b_reading_trails.setOpaque(true);
        cb_b_reading_trails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_reading_trailsActionPerformed(evt);
            }
        });
        bir.add(cb_b_reading_trails);

        jPopupMenu1.add(bir);

        help.setBackground(new java.awt.Color(51, 153, 255));
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/help.png"))); // NOI18N
        help.setText("HELP");
        help.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        help.setOpaque(true);
        jPopupMenu1.add(help);

        stand_by.setBackground(new java.awt.Color(51, 153, 255));
        stand_by.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stand_by.setForeground(new java.awt.Color(255, 255, 255));
        stand_by.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/maintenance.png"))); // NOI18N
        stand_by.setText("STAND BY");
        stand_by.setOpaque(true);
        stand_by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stand_byActionPerformed(evt);
            }
        });
        jPopupMenu1.add(stand_by);

        LOGOUT.setBackground(new java.awt.Color(51, 153, 255));
        LOGOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/s_reload.png"))); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.setOpaque(true);
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jPopupMenu1.add(LOGOUT);

        my_trans.setBackground(new java.awt.Color(255, 102, 0));

        my_maintenance.setBackground(new java.awt.Color(255, 102, 0));

        my_reports.setBackground(new java.awt.Color(255, 102, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Point of Sale");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("_");
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(194, 194, 194)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Transactions");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel6.setBackground(new java.awt.Color(255, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Maintenance");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/maintenance.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel9.setBackground(new java.awt.Color(255, 102, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Reports");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/reports.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel11.setBackground(new java.awt.Color(255, 102, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Stand by");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/standby.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel13.setBackground(new java.awt.Color(255, 102, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Log out");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/s_reload.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        cashout();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        hover(jLabel3);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        exit(jLabel3);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
//        hover2(jLabel7);
//        pm_tbl_users();
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        exit2(jLabel7);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    }//GEN-LAST:event_jLabel7MouseClicked

    private void cb_m_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_categoryActionPerformed
        category();
    }//GEN-LAST:event_cb_m_categoryActionPerformed

    private void cb_m_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_usersActionPerformed
        users();
    }//GEN-LAST:event_cb_m_usersActionPerformed

    private void cb_m_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_itemsActionPerformed
        items();
    }//GEN-LAST:event_cb_m_itemsActionPerformed

    private void cb_t_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_salesActionPerformed
        sales();
    }//GEN-LAST:event_cb_t_salesActionPerformed

    private void cb_r_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_salesActionPerformed
        sales_report();
    }//GEN-LAST:event_cb_r_salesActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        cashout();
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void cb_t_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_receiptsActionPerformed
        // TODO add your handling code here:
        receipts();
    }//GEN-LAST:event_cb_t_receiptsActionPerformed

    private void cb_t_stock_tranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_stock_tranferActionPerformed
        // TODO add your handling code here:
        stock_transfer();
    }//GEN-LAST:event_cb_t_stock_tranferActionPerformed

    private void cb_m_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_supplierActionPerformed
        supplier();
    }//GEN-LAST:event_cb_m_supplierActionPerformed

    private void cb_r_cash_countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_cash_countActionPerformed
        r_cash_count();
    }//GEN-LAST:event_cb_r_cash_countActionPerformed

    private void cb_r_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_receiptsActionPerformed
        // TODO add your handling code here:
        rpt_receipts();
    }//GEN-LAST:event_cb_r_receiptsActionPerformed

    private void cb_r_stock_transferredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stock_transferredActionPerformed
        // TODO add your handling code here:
        rpt_stock_transfer();
    }//GEN-LAST:event_cb_r_stock_transferredActionPerformed

    private void cb_r_stocks_left_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stocks_left_categoryActionPerformed
        rpt_stock_left_category();
    }//GEN-LAST:event_cb_r_stocks_left_categoryActionPerformed

    private void stand_byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stand_byActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_stand_byActionPerformed

    private void cb_r_sales_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_sales_itemsActionPerformed
        // TODO add your handling code here:
        sales_items();
    }//GEN-LAST:event_cb_r_sales_itemsActionPerformed

    private void cb_m_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_customersActionPerformed
        m_customers();
    }//GEN-LAST:event_cb_m_customersActionPerformed

    private void cb_m_discountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_discountsActionPerformed
        // TODO add your handling code here:
        m_discount();
    }//GEN-LAST:event_cb_m_discountsActionPerformed

    private void cb_m_uomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_uomActionPerformed
        m_uom();
    }//GEN-LAST:event_cb_m_uomActionPerformed

    private void cb_m_banksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_banksActionPerformed
        // TODO add your handling code here:
        m_banks();
    }//GEN-LAST:event_cb_m_banksActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cashout();
    }//GEN-LAST:event_formWindowClosing

    private void cb_r_stocks_left_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stocks_left_supplierActionPerformed
        // TODO add your handling code here:
        rpt_stock_left_supplier();
    }//GEN-LAST:event_cb_r_stocks_left_supplierActionPerformed

    private void cb_r_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_itemsActionPerformed
        // TODO add your handling code here:
        rpt_items_category();
    }//GEN-LAST:event_cb_r_itemsActionPerformed

    private void cb_t_inventory_adjusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_inventory_adjusterActionPerformed
        // TODO add your handling code here:
        adjust_inventory();
    }//GEN-LAST:event_cb_t_inventory_adjusterActionPerformed

    private void cb_b_x_readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_x_readingActionPerformed
        // TODO add your handling code here:
        z_reading();
    }//GEN-LAST:event_cb_b_x_readingActionPerformed

    private void cb_m_servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_servicesActionPerformed
        // TODO add your handling code here:
        m_services();
    }//GEN-LAST:event_cb_m_servicesActionPerformed

    private void cb_m_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_expensesActionPerformed
        // TODO add your handling code here:
        m_expenses();
    }//GEN-LAST:event_cb_m_expensesActionPerformed

    private void cb_t_purchase_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_purchase_orderActionPerformed
        // TODO add your handling code here:
        t_purchase_order();
    }//GEN-LAST:event_cb_t_purchase_orderActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        // TODO add your handling code here:
        t_purchase_order();
    }//GEN-LAST:event_transactionsActionPerformed

    private void cb_b_z_readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_z_readingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_b_z_readingActionPerformed

    private void cb_b_reading_trailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_reading_trailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_b_reading_trailsActionPerformed

    private void cb_r_purchase_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_purchase_orderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_r_purchase_orderActionPerformed

    private void cb_t_voiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_voiderActionPerformed
        t_voider();
    }//GEN-LAST:event_cb_t_voiderActionPerformed

    private void cb_r_voiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_voiderActionPerformed
        void_items();
    }//GEN-LAST:event_cb_r_voiderActionPerformed

    private void cb_r_patronage_refundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_patronage_refundActionPerformed
        r_patronage_refund();
    }//GEN-LAST:event_cb_r_patronage_refundActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        my_trans();
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        my_trans();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        my_maintenance();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        my_maintenance();
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        my_reports();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        my_reports();
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        login();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        cashout();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        hover(jLabel15);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        exit(jLabel15);
    }//GEN-LAST:event_jLabel15MouseExited

    private void cb_m_credit_cardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_credit_cardsActionPerformed
        m_credit_cards();
    }//GEN-LAST:event_cb_m_credit_cardsActionPerformed

    private void cb_m_printing_assemblyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_printing_assemblyActionPerformed
        m_printing_assembly();
    }//GEN-LAST:event_cb_m_printing_assemblyActionPerformed

    private void cb_m_category_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_category_groupActionPerformed
        m_category_group();
    }//GEN-LAST:event_cb_m_category_groupActionPerformed

    private void cb_m_waitersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_waitersActionPerformed
        m_waiters();
    }//GEN-LAST:event_cb_m_waitersActionPerformed

    private void cb_m_tablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_tablesActionPerformed
        m_tables();
    }//GEN-LAST:event_cb_m_tablesActionPerformed

    private void cb_t_disbursementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_disbursementsActionPerformed
        t_disbursements();
    }//GEN-LAST:event_cb_t_disbursementsActionPerformed

    private void cb_m_specActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_specActionPerformed
        m_spec();
    }//GEN-LAST:event_cb_m_specActionPerformed

    private void cb_r_patronage_refund1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_patronage_refund1ActionPerformed
        z_reading2();
    }//GEN-LAST:event_cb_r_patronage_refund1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Application.setSystemLookAndFeel();
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
//                new Pnl_Dashboard().setVisible(true);
                Pnl_Dashboard aw = new Pnl_Dashboard();
                String url = "/POS/img/5.png";
//                Wallpaper.do_set(url, aw.jPanel1);

                Toolkit tk = Toolkit.getDefaultToolkit();
                int xSize = ((int) tk.getScreenSize().
                        getWidth());
                int ySize = ((int) tk.getScreenSize().
                        getHeight());
                aw.setSize(xSize, ySize);
                Dimension d = aw.jPanel1.getSize();
//                Dimension d2 = aw.jXPanel2.getSize();
//                aw.jXPanel2.setSize(xSize, d2.height);
//                aw.jXPanel2.updateUI();
                aw.setVisible(true);
                aw.login();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LOGOUT;
    private javax.swing.JMenu bir;
    private javax.swing.JMenuItem cb_b_reading_trails;
    private javax.swing.JMenuItem cb_b_x_reading;
    private javax.swing.JMenuItem cb_b_z_reading;
    private javax.swing.JMenuItem cb_m_banks;
    private javax.swing.JMenuItem cb_m_category;
    private javax.swing.JMenuItem cb_m_category_group;
    private javax.swing.JMenuItem cb_m_credit_cards;
    private javax.swing.JMenuItem cb_m_customers;
    private javax.swing.JMenuItem cb_m_discounts;
    private javax.swing.JMenuItem cb_m_expenses;
    private javax.swing.JMenuItem cb_m_items;
    private javax.swing.JMenuItem cb_m_printing_assembly;
    private javax.swing.JMenuItem cb_m_services;
    private javax.swing.JMenuItem cb_m_spec;
    private javax.swing.JMenuItem cb_m_supplier;
    private javax.swing.JMenuItem cb_m_tables;
    private javax.swing.JMenuItem cb_m_uom;
    private javax.swing.JMenuItem cb_m_users;
    private javax.swing.JMenuItem cb_m_waiters;
    private javax.swing.JMenuItem cb_r_cash_count;
    private javax.swing.JMenuItem cb_r_items;
    private javax.swing.JMenuItem cb_r_patronage_refund;
    private javax.swing.JMenuItem cb_r_patronage_refund1;
    private javax.swing.JMenuItem cb_r_purchase_order;
    private javax.swing.JMenuItem cb_r_receipts;
    private javax.swing.JMenuItem cb_r_sales;
    private javax.swing.JMenuItem cb_r_sales_items;
    private javax.swing.JMenuItem cb_r_stock_transferred;
    private javax.swing.JMenuItem cb_r_stocks_left_category;
    private javax.swing.JMenuItem cb_r_stocks_left_supplier;
    private javax.swing.JMenuItem cb_r_voider;
    private javax.swing.JMenuItem cb_t_disbursements;
    private javax.swing.JMenuItem cb_t_inventory_adjuster;
    private javax.swing.JMenuItem cb_t_purchase_order;
    private javax.swing.JMenuItem cb_t_receipts;
    private javax.swing.JMenuItem cb_t_sales;
    private javax.swing.JMenuItem cb_t_stock_tranfer;
    private javax.swing.JMenuItem cb_t_voider;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDesktopPane jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu maintenance;
    private javax.swing.JPopupMenu my_maintenance;
    private javax.swing.JPopupMenu my_reports;
    private javax.swing.JPopupMenu my_trans;
    private javax.swing.JMenu reports;
    private javax.swing.JMenuItem stand_by;
    private javax.swing.JMenu transactions;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        Main.MyDB.setNames("db_fortune_three");
        String business_name = System.getProperty("business_name", "SYNAPSE SOFTWARE TECHNOLOGY");
        String slogan = System.getProperty("slogan", "INTEGRATING BUSINESS THROUGH TECHNOLOGY");
//        lbl_business_name.setText(business_name);
//        init_trans();
    }

    private void init_trans() {
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(transactions);

    }

    public JDesktopPane pane() {
        return jPanel1;
    }

//    public JXPanel pane2() {
//        return jXPanel2;
//    }
    public void login() {
        Window p = (Window) this;
        Dlg_touchscreen_login nd = Dlg_touchscreen_login.create(p, true);
        nd.setTitle("");
        nd.setCallback(new Dlg_touchscreen_login.Callback() {
            @Override
            public void ok(CloseDialog closeDialog, Dlg_touchscreen_login.OutputData data) {
                closeDialog.ok();
                jPanel1.removeAll();
                jPanel1.removeAll();

                Dimension d = jPanel1.getSize();
                String url = "/POS/img/5.png";
                jPanel1.updateUI();
                set_account();
                if (Users.user_level == 1 && Users.t_sales.equals("1")) {
                    sales();
                } else {
                    Pnl_Dashboard pnl = new Pnl_Dashboard();
                    Toolkit tk = Toolkit.getDefaultToolkit();
                    int xSize = ((int) tk.getScreenSize().
                            getWidth());
                    int ySize = ((int) tk.getScreenSize().
                            getHeight());
                    pnl.setSize(xSize, ySize);
                    pnl.setVisible(true);
                    pnl.set_account();

                }
            }

        });
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().
                getWidth());
        int ySize = ((int) tk.getScreenSize().
                getHeight());
        nd.setSize(xSize, ySize);
        nd.setVisible(true);
    }

    public void set_account() {

        if (Users.user_level == 0) {

            cb_r_patronage_refund.setVisible(true);
            cb_r_cash_count.setVisible(true);
            cb_r_voider.setVisible(true);
            cb_b_x_reading.setVisible(true);
            cb_r_patronage_refund1.setVisible(true);

            cb_r_purchase_order.setVisible(true);
            my_reports.add(cb_r_patronage_refund);
            my_reports.add(cb_r_cash_count);
            my_reports.add(cb_r_voider);
            my_reports.add(cb_b_x_reading);

            my_reports.add(cb_r_purchase_order);
            my_reports.add(cb_r_patronage_refund1);

            cb_b_x_reading.setVisible(true);

        } else {
            cb_r_patronage_refund.setVisible(false);
            cb_r_cash_count.setVisible(false);
            cb_r_voider.setVisible(false);
            cb_b_x_reading.setVisible(false);

            cb_r_purchase_order.setVisible(false);

            cb_t_purchase_order.setVisible(false);

        }

        if (Users.r_sales.equals("0")) {

            cb_r_sales.setVisible(false);
        } else {
            my_reports.add(cb_r_sales);
            cb_r_sales.setVisible(true);
        }
        if (Users.user_level == 0) {
            cb_r_sales_items.setVisible(true);
            my_reports.add(cb_r_sales_items);
        } else {
            cb_r_sales_items.setVisible(false);
        }
        if (Users.t_receipts.equals("0")) {
            cb_t_receipts.setVisible(false);
        } else {
            my_trans.add(cb_t_receipts);
            cb_t_receipts.setVisible(true);
        }

        if (Users.user_level == 0) {
            my_trans.add(cb_t_voider);
            cb_t_voider.setVisible(true);

        } else {
            cb_t_voider.setVisible(false);

        }
        if (Users.t_inventory_adjuster.equals("0")) {
            cb_t_inventory_adjuster.setVisible(false);
        } else {
            my_trans.add(cb_t_inventory_adjuster);
            cb_t_inventory_adjuster.setVisible(true);
        }

        if (Users.t_stock_transfer.equals("0")) {

            cb_t_stock_tranfer.setVisible(false);
        } else {
            my_trans.add(cb_t_stock_tranfer);
            cb_t_stock_tranfer.setVisible(true);
        }

        //zzz
        if (Users.t_sales.equals("0")) {
            cb_t_sales.setVisible(false);
        } else {
            my_trans.add(cb_t_sales);
            cb_t_sales.setVisible(true);
        }

        if (Users.m_items.equals("0")) {

            cb_m_items.setVisible(false);
        } else {
            my_maintenance.add(cb_m_items);
            cb_m_items.setVisible(true);
        }

        if (Users.m_category.equals("0")) {

            cb_m_category.setVisible(false);

        } else {
            my_maintenance.add(cb_m_category);
            cb_m_category.setVisible(true);
        }

        if (Users.m_users.equals("0")) {

            cb_m_users.setVisible(false);
        } else {
            my_maintenance.add(cb_m_users);
            cb_m_users.setVisible(true);
        }

        if (Users.m_uom.equals("0")) {

            cb_m_uom.setVisible(false);
        } else {
            my_maintenance.add(cb_m_uom);
            cb_m_uom.setVisible(true);
        }

        if (Users.m_suppliers.equals("0")) {

            cb_m_supplier.setVisible(false);
        } else {
            my_maintenance.add(cb_m_supplier);
            cb_m_supplier.setVisible(true);
        }

        if (Users.r_cash_count.equals("0")) {

            cb_r_cash_count.setVisible(false);
        } else {
            my_reports.add(cb_r_cash_count);
            cb_r_cash_count.setVisible(true);
        }

        if (Users.r_receipts.equals("0")) {

            cb_r_receipts.setVisible(false);
        } else {
            my_reports.add(cb_r_receipts);
            cb_r_receipts.setVisible(true);
        }

        if (Users.r_stock_transferred.equals("0")) {

            cb_r_stock_transferred.setVisible(false);
        } else {
            my_reports.add(cb_r_stock_transferred);
            cb_r_stock_transferred.setVisible(true);
        }

        if (Users.r_stock_take.equals("0")) {
            cb_r_stocks_left_category.setVisible(false);
        } else {
            my_reports.add(cb_r_stocks_left_category);
            cb_r_stocks_left_category.setVisible(true);
        }

        if (Users.m_customers.equals("0")) {
            cb_m_customers.setVisible(false);
        } else {
            my_maintenance.add(cb_m_customers);
            cb_m_customers.setVisible(true);
        }
        if (Users.m_discount.equals("0")) {
            cb_m_discounts.setVisible(false);
        } else {
            my_maintenance.add(cb_m_discounts);
            cb_m_discounts.setVisible(true);
        }
        if (Users.m_banks.equals("0")) {
            cb_m_banks.setVisible(false);
        } else {
            my_maintenance.add(cb_m_banks);
            cb_m_banks.setVisible(true);
        }
        if (Users.r_stock_left_supplier.equals("0")) {
            cb_r_stocks_left_supplier.setVisible(false);
        } else {
            my_reports.add(cb_r_stocks_left_supplier);
            cb_r_stocks_left_supplier.setVisible(true);
        }

        if (Users.user_level == 0) {
            cb_m_banks.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_category.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_category_group.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_credit_cards.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_customers.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_discounts.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_expenses.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_items.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_printing_assembly.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_services.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_tables.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_supplier.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_uom.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_users.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);
            cb_m_waiters.setVisible(true);
            my_maintenance.add(cb_t_inventory_adjuster);

            cb_t_inventory_adjuster.setVisible(true);
            my_trans.add(cb_t_inventory_adjuster);
            cb_t_purchase_order.setVisible(true);
            my_trans.add(cb_t_purchase_order);
            cb_t_receipts.setVisible(true);
            my_trans.add(cb_t_receipts);
            cb_t_sales.setVisible(true);
            my_trans.add(cb_t_sales);
            cb_t_stock_tranfer.setVisible(true);
            my_trans.add(cb_t_stock_tranfer);
            cb_t_voider.setVisible(true);
            my_trans.add(cb_t_voider);

            cb_r_items.setVisible(true);
            my_reports.add(cb_r_items);
            cb_r_cash_count.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_patronage_refund.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_receipts.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_sales.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_sales_items.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_stock_transferred.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_stocks_left_category.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_stocks_left_supplier.setVisible(true);
            my_reports.add(cb_r_cash_count);
            cb_r_voider.setVisible(true);
            my_reports.add(cb_r_voider);

            cb_t_purchase_order.setVisible(true);
            my_trans.add(cb_t_purchase_order);

            cb_m_credit_cards.setVisible(true);
            my_maintenance.add(cb_m_credit_cards);

            cb_m_printing_assembly.setVisible(true);
            my_maintenance.add(cb_m_printing_assembly);

            cb_m_category_group.setVisible(true);
            my_maintenance.add(cb_m_category_group);

            cb_m_waiters.setVisible(true);
            my_maintenance.add(cb_m_waiters);

            cb_m_expenses.setVisible(true);
            my_maintenance.add(cb_m_expenses);

            cb_m_tables.setVisible(true);
            my_maintenance.add(cb_m_tables);

            cb_t_disbursements.setVisible(true);
            my_trans.add(cb_t_disbursements);
            cb_m_spec.setVisible(true);
            my_maintenance.add(cb_m_spec);
        } else {
            cb_t_purchase_order.setVisible(false);
            cb_m_credit_cards.setVisible(false);
            cb_m_printing_assembly.setVisible(false);
            cb_m_category_group.setVisible(false);
            cb_m_waiters.setVisible(false);
            cb_m_expenses.setVisible(false);
            cb_m_tables.setVisible(false);
            cb_t_disbursements.setVisible(false);
            cb_m_spec.setVisible(false);
        }

        cb_r_patronage_refund.setVisible(false);
    }

    private void hover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(230, 227, 227));
        lbl.setForeground(new java.awt.Color(0, 0, 0));
    }

    private void exit(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(255, 255, 255));
        lbl.setForeground(new java.awt.Color(153, 153, 153));
    }

    private void hover2(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(29, 141, 253));

    }

    private void exit2(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(51, 153, 255));
    }

    private void pm_tbl_users() {

        Point l = jLabel7.getLocation();
        jPopupMenu1.show(this, l.x, l.y + 34);
    }

    private void users() {
        Dlg_users dtc = new Dlg_users();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Users");
    }

    private void items() {
        Dlg_items dtc = new Dlg_items();
        MyFrame.set(dtc.getSurface(), jPanel1, "Items");
    }

    private void category() {
        Dlg_category dtc = new Dlg_category();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Category");
    }

    public void sales() {
//        final Dlg_sales dtc = new Dlg_sales();
//        MyFrame.set(dtc.getSurface(), jPanel1, "Sales");
        Window p = (Window) this;
        Dlg_touchscreen nd = Dlg_touchscreen.create(p, true);
        nd.setTitle("");
//        nd.do_pass(services);
        nd.setCallback(new Dlg_touchscreen.Callback() {

            @Override
            public void ok(CloseDialog closeDialog, Dlg_touchscreen.OutputData data) {
                closeDialog.ok();

            }
        });

        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().
                getWidth());
        int ySize = ((int) tk.getScreenSize().
                getHeight());
        nd.setSize(xSize, ySize);
        nd.setVisible(true);
    }

    private void sales_report() {
        Dlg_report_all_sales dtc = new Dlg_report_all_sales();
        MyFrame.set(dtc.getSurface(), jPanel1, "Sales Report");
    }

    private void cashout() {
        if (Users.user_level == 0) {
            System.exit(1);
        } else {

            if (Users.is_active == 0) {

                Window p = (Window) this;
                Dlg_cash_out nd = Dlg_cash_out.create(p, true);
                nd.setTitle("");
                nd.do_pass_in(Users.checks, Users.drawer);
                nd.setCallback(new Dlg_cash_out.Callback() {

                    @Override
                    public void ok(CloseDialog closeDialog, Dlg_cash_out.OutputData data) {
                        closeDialog.ok();
                        S1_cash_drawer.edit_cash_drawer(data.drawer);
                        S1_cash_drawer_checks.add_cash_drawer_checks(data.drawer.checks);
//                        S1_cash_drawer_expenses.add_cash_drawer_checks(data.drawer.exp);
                        Alert.set(0, "THANK YOU, HAVE A NICE DAY");
                        System.exit(1);
//                    login`
                    }
                });

                nd.setLocationRelativeTo(this);
                nd.setVisible(true);
            }
            if (Users.is_active == 1) {
//                JOptionPane.showMessageDialog(null, "adadad");
                Window p = (Window) this;
                Dlg_cash_out nd = Dlg_cash_out.create(p, true);
                nd.setTitle("");
                nd.do_pass(Users.checks, Users.drawer);
                nd.setCallback(new Dlg_cash_out.Callback() {

                    @Override
                    public void ok(CloseDialog closeDialog, Dlg_cash_out.OutputData data) {
                        closeDialog.ok();
                        S1_cash_drawer.edit_cash_drawer(data.drawer);
                        Alert.set(0, "THANK YOU, HAVE A NICE DAY");
                        System.exit(1);
//                    login`
                    }
                });
                nd.setLocationRelativeTo(this);
                nd.setVisible(true);
            }

        }
    }

    private void receipts() {
        Dlg_receipts dtc = new Dlg_receipts();
        MyFrame.set(dtc.getSurface(), jPanel1, "Receipts");
    }

    private void sales_items() {
        Dlg_sales_by_item dtc = new Dlg_sales_by_item();
        MyFrame.set(dtc.getSurface(), jPanel1, "Sales by Item");
    }

    private void stock_transfer() {
        Dlg_stock_transfer dtc = new Dlg_stock_transfer();
        MyFrame.set(dtc.getSurface(), jPanel1, "Stock Transfer");
    }

    private void supplier() {
        Dlg_supplier dtc = new Dlg_supplier();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Supplier");
    }

    private void rpt_cash_drawer() {
        Dlg_rpt_cashdrawer dtc = new Dlg_rpt_cashdrawer();
        MyFrame.set(dtc.getSurface(), jPanel1, "Cash Count Report");
    }

    private void rpt_receipts() {
        Dlg_report_receipts dtc = new Dlg_report_receipts();
        MyFrame.set(dtc.getSurface(), jPanel1, "Receipts Report");
    }

    private void rpt_stock_transfer() {
        Dlg_rpt_stock_transfer dtc = new Dlg_rpt_stock_transfer();
        MyFrame.set(dtc.getSurface(), jPanel1, "Stock Transfer Report");
    }

    private void rpt_stock_left_category() {
        Dlg_report_stock_left_category dtc = new Dlg_report_stock_left_category();
        MyFrame.set(dtc.getSurface(), jPanel1, "Stocks Left by category Report");
    }

    private void rpt_stock_left_supplier() {
        Dlg_report_stock_left_supplier dtc = new Dlg_report_stock_left_supplier();
        MyFrame.set(dtc.getSurface(), jPanel1, "Stocks Left by Supplier Report");
    }

    private void rpt_items_category() {
        Dlg_report_items_by_category dtc = new Dlg_report_items_by_category();
        MyFrame.set(dtc.getSurface(), jPanel1, "Item Category Report");
    }

    private void m_customers() {
        Dlg_customers dtc = new Dlg_customers();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Customers");
    }

    private void m_discount() {
        Dlg_discounts dtc = new Dlg_discounts();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Discounts");
    }

    private void m_uom() {
        Dlg_uom dtc = new Dlg_uom();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Unit of Measure");
    }

    private void m_banks() {
        Dlg_banks dtc = new Dlg_banks();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Banks");
    }

    private void adjust_inventory() {
        Dlg_new_inventory dtc = new Dlg_new_inventory();
        MyFrame.set(dtc.getSurface(), jPanel1, "Adjuster");
    }

    private void z_reading() {
        Dlg_x_reading dtc = new Dlg_x_reading();
        MyFrame.set(dtc.getSurface(), jPanel1, "Sales Summary");
    }

     private void z_reading2() {
        Dlg_z_reading dtc = new Dlg_z_reading();
        MyFrame.set(dtc.getSurface(), jPanel1, "Sales Summary");
    }
     
    private void t_purchase_order() {
        Dlg_purchase_order dtc = new Dlg_purchase_order();
        MyFrame.set(dtc.getSurface(), jPanel1, "Purchase Order");
    }

    private void m_services() {
        Dlg_services dtc = new Dlg_services();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Services");
    }

    private void m_expenses() {
        Dlg_expenses dtc = new Dlg_expenses();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Disbursements");
    }

    private void m_credit_cards() {
        Dlg_credit_cards dtc = new Dlg_credit_cards();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Credit_cards");
    }

    private void m_printing_assembly() {
        Dlg_printing_assembly dtc = new Dlg_printing_assembly();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Printing Assembly");
    }

    private void m_category_group() {
        Dlg_inv_category_group dtc = new Dlg_inv_category_group();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Category Group");
    }

    private void m_waiters() {
        Dlg_waiters dtc = new Dlg_waiters();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Waiters");
    }

    private void m_tables() {
        Dlg_tables dtc = new Dlg_tables();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Tables");
    }

    private void m_spec() {
        Dlg_order_spefications dtc = new Dlg_order_spefications();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Order Specification");
    }

    private void r_patronage_refund() {
        Dlg_patronage_refund dtc = new Dlg_patronage_refund();
        MyFrame.set(dtc.getSurface(), jPanel1, "Patronage Refund");
    }

    private void t_voider() {
        Dlg_voider dtc = new Dlg_voider();
        MyFrame.set(dtc.getSurface(), jPanel1, "Voider");
    }

    private void r_cash_count() {
        Dlg_cashcount dtc = new Dlg_cashcount();
        MyFrame.set(dtc.getSurface(), jPanel1, "Cash Count Report");
    }

    private void void_items() {
        Dlg_void_items nd = new Dlg_void_items();
        MyFrame.set(nd.getSurface(), jPanel1, "Void Sales Report");
    }

    private void my_trans() {
        Point l = jPanel3.getLocation();
        my_trans.show(this, l.x, l.y + 60);
    }

    private void my_maintenance() {
        Point l = jPanel4.getLocation();
        my_maintenance.show(this, l.x, l.y + 60);
    }

    private void my_reports() {
        Point l = jPanel7.getLocation();
        my_reports.show(this, l.x, l.y + 60);
    }

    private void t_disbursements() {
        Dlg_disbursements dtc = new Dlg_disbursements();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Disbursements");
    }

}
