/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package POS.test;

import POS.cash_drawer.Dlg_cashin;
import POS.items.Dlg_items;
import POS.users.Dlg_users;
import POS.util.Center;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import javax.swing.JInternalFrame;
import mijzcx.synapse.desk.utils.CloseDialog;
import mijzcx.synapse.desk.utils.KeyMapping;
import mijzcx.synapse.desk.utils.KeyMapping.KeyAction;

/**
 *
 * @author Maytopacka
 */
public class Dlg_aw extends javax.swing.JDialog {

    /**
     * Creates new form Dlg_aw
     */
    //<editor-fold defaultstate="collapsed" desc=" callback ">
    private Callback callback;

    public void setCallback(Callback callback) {
        this.callback = callback;


    }

    public static interface Callback {

        void ok(CloseDialog closeDialog, OutputData data);
    }

    public static class InputData {
    }

    public static class OutputData {
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" Constructors ">
    private Dlg_aw(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    private Dlg_aw(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    public Dlg_aw() {
        super();
        initComponents();
        myInit();

    }
    private Dlg_aw myRef;

    private void setThisRef(Dlg_aw myRef) {
        this.myRef = myRef;
    }
    private static java.util.Map<Object, Dlg_aw> dialogContainer = new java.util.HashMap();

    public static void clearUpFirst(java.awt.Window parent) {
        if (dialogContainer.containsKey(parent)) {
            dialogContainer.remove(parent);
        }
    }

    public static Dlg_aw create(java.awt.Window parent, boolean modal) {

        if (modal) {
            return create(parent, ModalityType.APPLICATION_MODAL);
        }

        return create(parent, ModalityType.MODELESS);

    }

    public static Dlg_aw create(java.awt.Window parent, java.awt.Dialog.ModalityType modalType) {

        if (parent instanceof java.awt.Frame) {

            Dlg_aw dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_aw((java.awt.Frame) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().
                        log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        if (parent instanceof java.awt.Dialog) {
            Dlg_aw dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_aw((java.awt.Dialog) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().
                        log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        return null;

    }
    //</editor-fold>    

    //<editor-fold defaultstate="collapsed" desc=" main ">
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.
                    getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        Dlg_aw dialog = Dlg_aw.create(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" added ">
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible == true) {
            getContentPane().
                    removeAll();
            initComponents();
            myInit();
            repaint();
        }


    }

    public javax.swing.JPanel getSurface() {
        return (javax.swing.JPanel) getContentPane();
    }

    public void nullify() {
        myRef.setVisible(false);
        myRef = null;
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_snewtbl.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        init_key();
//        users();
//        items();
        set();
    }

    public void do_pass() {
    }
    // <editor-fold defaultstate="collapsed" desc="Key">

    private void disposed() {
        this.dispose();
    }

    private void init_key() {
        KeyMapping.mapKeyWIFW(getSurface(),
                KeyEvent.VK_ESCAPE, new KeyAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
//                btn_0.doClick();
                disposed();
            }
        });
    }
    // </editor-fold>

    private void set() {
        final JInternalFrame p2 = new JInternalFrame("", true, true, true, true);
        Dlg_cashin d = new Dlg_cashin();
        p2.add(d.getSurface());
        p2.show();
        p2.setVisible(true);
        p2.setSize(400,400);
        p2.setLayout(new BorderLayout());
        jDesktopPane1.add(p2);
        
    }

    private void users() {
        Dlg_users dtc = new Dlg_users();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p2 = new JInternalFrame();
        p2.add(dtc.getSurface());
        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setClosable(true);
        p2.setIconifiable(true);
        p2.setMaximizable(true);
        p2.setLayer(0);
        System.out.println("");
        p2.setSize(width + 10, height + 20);
        try {
            p2.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        p2.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        p2.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent fe) {
                p2.toFront();
            }

            @Override
            public void focusLost(FocusEvent fe) {
                p2.toBack();
            }
        });
        p2.setVisible(true);
        jDesktopPane1.add(p2);
        Center.setCenter(p2);
//        jPanel1.setLayout(new BorderLayout());
    }

    private void items() {
        Dlg_items dtc = new Dlg_items();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p2 = new JInternalFrame();
        p2.add(dtc.getSurface());
        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setClosable(true);
        p2.setIconifiable(true);
        p2.setMaximizable(true);
//        p2.setLayer(1);
        System.out.println("");
        p2.setSize(width + 10, height + 20);

        p2.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        p2.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent fe) {
                p2.toFront();
            }

            @Override
            public void focusLost(FocusEvent fe) {
                p2.toBack();
            }
        });
        p2.setVisible(true);

        jDesktopPane1.add(p2);
        Center.setCenter(p2);
//        jPanel1.setLayout(new BorderLayout());
    }
}
